-- ============================================================
-- SphereSync Coach — B5.5: task lineage columns
--
-- Add the columns the Coach needs to auto-create tasks with full
-- auditability, dedup, and reversibility. Applied to BOTH existing
-- task tables (spheresync_tasks + pipeline_tasks).
--
-- Semantics:
--   source            'agent' | 'coach' | 'system'
--                     - 'agent': created by the agent themselves
--                     - 'coach': created by ai-coach-agent (auto-suggested)
--                     - 'system': generated by other automation (e.g.,
--                       the existing SphereSync weekly-cadence job)
--                     NULL means legacy row predating this column — treat
--                     as 'agent' for UI purposes.
--   coach_reasoning   One-sentence explanation for Coach-created tasks.
--                     Surfaced in the task UI as a "Why this task?" tooltip.
--   coach_created_at  Timestamp of the Coach tick that produced this task.
--                     Used for dedup (7-day window) and TTL cleanup (30-day).
--   coach_dismissed_at Set when agent dismisses a Coach suggestion.
--                     Non-null rows are hidden from active lists.
--                     Kept on disk for learning-loop signal in a future phase.
--
-- All columns are nullable and additive. Zero risk for existing rows.
-- Reference: docs/spheresync-coach-design.md § "Auto-task creation"
-- ============================================================

-- 1. Task source columns on spheresync_tasks
ALTER TABLE public.spheresync_tasks
  ADD COLUMN IF NOT EXISTS source             TEXT,
  ADD COLUMN IF NOT EXISTS coach_reasoning    TEXT,
  ADD COLUMN IF NOT EXISTS coach_created_at   TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS coach_dismissed_at TIMESTAMPTZ;

COMMENT ON COLUMN public.spheresync_tasks.source IS
  'Who created this task: ''agent'' | ''coach'' | ''system''. NULL = legacy row predating the column (treat as agent-created in UI).';
COMMENT ON COLUMN public.spheresync_tasks.coach_reasoning IS
  'One-sentence Coach rationale for why this task exists. Shown as a "Why?" tooltip in the UI.';
COMMENT ON COLUMN public.spheresync_tasks.coach_created_at IS
  'When the Coach tick produced this task. Used for dedup (7d window) + TTL (30d cleanup).';
COMMENT ON COLUMN public.spheresync_tasks.coach_dismissed_at IS
  'Set when the agent dismisses a Coach suggestion. Dismissed tasks are hidden from active lists but kept for learning-loop signal.';

-- 2. Same columns on pipeline_tasks
ALTER TABLE public.pipeline_tasks
  ADD COLUMN IF NOT EXISTS source             TEXT,
  ADD COLUMN IF NOT EXISTS coach_reasoning    TEXT,
  ADD COLUMN IF NOT EXISTS coach_created_at   TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS coach_dismissed_at TIMESTAMPTZ;

COMMENT ON COLUMN public.pipeline_tasks.source IS
  'Who created this task: ''agent'' | ''coach'' | ''system''.';
COMMENT ON COLUMN public.pipeline_tasks.coach_reasoning IS
  'One-sentence Coach rationale.';
COMMENT ON COLUMN public.pipeline_tasks.coach_created_at IS
  'When the Coach tick produced this task.';
COMMENT ON COLUMN public.pipeline_tasks.coach_dismissed_at IS
  'Set when agent dismisses a Coach suggestion.';

-- 3. Indexes

-- Fast filter: "active Coach tasks for this agent/contact" — used by dedup
-- logic (7d window query) and UI rendering of the ✨ badge list.
CREATE INDEX IF NOT EXISTS idx_spheresync_tasks_coach_active
  ON public.spheresync_tasks(agent_id, lead_id, coach_created_at DESC)
  WHERE source = 'coach' AND coach_dismissed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_pipeline_tasks_coach_active
  ON public.pipeline_tasks(agent_id, contact_id, coach_created_at DESC)
  WHERE source = 'coach' AND coach_dismissed_at IS NULL;

-- TTL cleanup: "Coach tasks older than 30 days that were never acted on."
-- Used by the B5.8 nightly cleanup cron.
CREATE INDEX IF NOT EXISTS idx_spheresync_tasks_coach_ttl
  ON public.spheresync_tasks(coach_created_at ASC)
  WHERE source = 'coach' AND completed = false AND coach_dismissed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_pipeline_tasks_coach_ttl
  ON public.pipeline_tasks(coach_created_at ASC)
  WHERE source = 'coach' AND completed = false AND coach_dismissed_at IS NULL;

-- 4. No RLS changes — the new columns inherit policies from the parent table.
